import './bootstrap';
const sidebar=document.querySelector('[data-sidebar]'),overlay=document.querySelector('[data-sidebar-overlay]');
const toggleSidebar=open=>{sidebar?.classList.toggle('-translate-x-full',!open);overlay?.classList.toggle('hidden',!open);document.body.classList.toggle('overflow-hidden',open)};
document.querySelector('[data-sidebar-open]')?.addEventListener('click',()=>toggleSidebar(true));overlay?.addEventListener('click',()=>toggleSidebar(false));
document.querySelectorAll('[data-confirm]').forEach(form=>form.addEventListener('submit',event=>{if(!window.confirm(form.dataset.confirm))event.preventDefault()}));
document.querySelectorAll('[data-href]').forEach(row=>row.addEventListener('click',()=>window.location.assign(row.dataset.href)));
const toast=document.querySelector('[data-toast]'),closeToast=()=>toast?.remove();document.querySelector('[data-toast-close]')?.addEventListener('click',closeToast);if(toast)window.setTimeout(closeToast,4500);
const clientSelect=document.querySelector('[data-client-select]'),businessSelect=document.querySelector('[data-business-select]');clientSelect?.addEventListener('change',()=>{businessSelect.querySelectorAll('option[data-client]').forEach(option=>option.hidden=clientSelect.value!==''&&option.dataset.client!==clientSelect.value);if(businessSelect.selectedOptions[0]?.hidden)businessSelect.value=''});
const paymentProject=document.querySelector('[data-payment-project]'),periodSelect=document.querySelector('#billing_period_id'),filterPeriods=()=>periodSelect?.querySelectorAll('option[data-project]').forEach(option=>option.hidden=paymentProject?.value&&option.dataset.project!==paymentProject.value);paymentProject?.addEventListener('change',filterPeriods);filterPeriods();
const search=document.querySelector('[data-global-search]');if(search){const input=search.querySelector('input'),panel=search.querySelector('[data-search-results]');let timer;input.addEventListener('input',()=>{clearTimeout(timer);const query=input.value.trim();if(query.length<2){panel.classList.add('hidden');panel.innerHTML='';return}timer=setTimeout(async()=>{try{const response=await fetch(`${search.dataset.url}?q=${encodeURIComponent(query)}`,{headers:{Accept:'application/json'}}),data=await response.json(),labels={projects:'Projets',clients:'Clients',businesses:'Entreprises'};panel.innerHTML=Object.entries(data).map(([group,items])=>items.length?`<p class="search-group">${labels[group]}</p>${items.map(item=>`<a class="search-result" href="${item.url}"><strong>${escapeHtml(item.label)}</strong><span>${escapeHtml(item.meta)}</span></a>`).join('')}`:'').join('')||'<p class="p-4 text-sm text-muted">Aucun résultat.</p>';panel.classList.remove('hidden')}catch{panel.innerHTML='<p class="p-4 text-sm text-danger">Recherche indisponible.</p>';panel.classList.remove('hidden')}},280)});document.addEventListener('click',event=>{if(!search.contains(event.target))panel.classList.add('hidden')});document.addEventListener('keydown',event=>{if(event.key==='Escape')panel.classList.add('hidden')})}
document.querySelectorAll('table').forEach(table=>{const labels=[...table.querySelectorAll('thead th')].map(th=>th.textContent.trim());table.querySelectorAll('tbody tr').forEach(row=>[...row.children].forEach((cell,index)=>cell.dataset.label=labels[index]||''))});
function escapeHtml(value){const div=document.createElement('div');div.textContent=value??'';return div.innerHTML}
